Initialisation
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #1
Opened 2022-04-14 14:49 UTC by Chloebert

2022-04-14 14:51 UTC, Ysedda approved these changes

2022-04-14 14:54 UTC, baloolc submitted a review, later dismissed

2022-04-14 15:20 UTC, ThibaultFoure requested changes

2022-04-14 15:20 UTC, ThibaultFoure commented on public/assets/css/style.css
> +    --spacing: 1rem;
Pas la meilleure idée de définir des spacings en valeurs relatives, vous allez avoir des surprises en fonction des tailles d'écran

2022-04-14 15:20 UTC, ThibaultFoure commented on public/assets/css/style.css
> +    --big-spacing: 4rem;
Faites en sorte de définir un spacing de base et les suivants en seront des multiples

2022-04-14 15:20 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
C'est peut-être du formatage automatique mais l'indentation n'est pas bonne et le endblock devrait être à la ligne

2022-04-15 07:45 UTC, JSDerouet approved these changes

2022-04-15 07:49 UTC, DESCARAVAGE approved these changes

2022-04-15 07:50 UTC, DESCARAVAGE approved these changes

2022-04-15 07:55 UTC, ThibaultFoure approved these changes

2022-04-15 07:56 UTC, merged