Fix b footer
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #115
Opened 2022-04-26 14:06 UTC by baloolc

2022-04-26 14:31 UTC, Chloebert submitted a review, later dismissed

2022-04-26 17:49 UTC, ThibaultFoure requested changes

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +    height: 476px;
Ça fonctionne en responsive la taille fixe sur le footer ? :thinking:

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +
ligne vide ici

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +
ici aussi

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +}
En ciblant uniquement le tbody il me semble que ça fonctionne

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +    width: 50%;
Faisable avec bootstrap

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +    text-align: center;
faisable avec bootstrap

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +}
Très mauvaise idée de donner une taille fixe à la map, ça va tout péter en responsive

2022-04-26 17:49 UTC, ThibaultFoure commented on public/assets/css/footer.css
>  }
![obama-confused](https://user-images.githubusercontent.com/79161810/165359504-3f276a31-5e50-4393-9e91-296e37761170.gif)

2022-04-26 17:49 UTC, ThibaultFoure commented on src/View/Component/_footer.html.twig
> +					Retrouvez-nous sur nôtre réseau social:
notre sans accent

2022-04-26 17:49 UTC, ThibaultFoure commented on src/View/Component/_footer.html.twig
> +			<table class="table table-hover flex-column" aria-label="hourly">
le flex-column ne sert pas ici, sans d-flex il n'a aucun effet

2022-04-26 17:49 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +				{% endblock %}
Ça vaut pour tout le monde, n'abusez pas des ctrl shift I sur des fichiers qui sont déjà push, ça évitera des lignes de modifs juste pour un retour à la ligne

2022-04-27 13:16 UTC, Chloebert submitted a review, later dismissed

2022-04-27 15:05 UTC, ThibaultFoure requested changes

2022-04-27 15:05 UTC, ThibaultFoure commented on public/assets/css/footer.css
> +    letter-spacing: 2px;
illégal, vous définissez des variables pour éviter ce genre de choses, et essaie de le faire avec bootstrap avant de passer en css

2022-04-27 15:05 UTC, ThibaultFoure commented on src/View/Component/_footer.html.twig
> +			<div class="title-footer d-flex justify-content-center align-item-center mt-2 p-2 mb-4">
align-items avec un s là ta classe ne fait rien

2022-04-28 08:43 UTC, JSDerouet submitted a review, later dismissed

2022-04-28 08:52 UTC, ThibaultFoure requested changes
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

2022-04-28 08:52 UTC, ThibaultFoure commented on src/View/Component/_footer.html.twig
> +			<div class="title-footer d-flex justify-content-center align-item-center mt-2 p-2 mb-4">
C'est toujours là

2022-04-28 08:52 UTC, ThibaultFoure commented on src/View/Component/_footer.html.twig
> +			<div class="title-footer d-flex justify-content-center align-item-center mt-2 mb-2 p-2">
align-itemsssssssssssssssssssssssssssssssss

2022-04-28 09:06 UTC, Chloebert approved these changes

2022-04-28 10:13 UTC, ThibaultFoure approved these changes

2022-04-28 10:23 UTC, merged