S02 us19 admin cloth show
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #116
Opened 2022-04-26 14:54 UTC by Ysedda

2022-04-26 15:02 UTC, Chloebert submitted a review, later dismissed

2022-04-26 17:58 UTC, ThibaultFoure requested changes

2022-04-26 17:58 UTC, ThibaultFoure commented on src/View/Admin/Cloth/show.html.twig
> +  <div class="d-flex col-8 col-md-8 flex-row justify-content-between align-self-center mt-3 align-items-center">
par défaut quand tu mets un d-flex, tu es en flex-row pas besoin de le respécifier

2022-04-26 17:58 UTC, ThibaultFoure commented on src/View/Admin/Cloth/show.html.twig
> +	<ul class="list-group col-8 col-md-8 mx-auto mt-1">
même commentaire que plus haut, pas besoin de col-md si tu définis un col

2022-04-27 06:58 UTC, Chloebert approved these changes

2022-04-27 09:10 UTC, ThibaultFoure approved these changes

2022-04-27 09:11 UTC, merged