S1 us11 form
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #119
Opened 2022-04-27 09:10 UTC by DESCARAVAGE

2022-04-27 09:36 UTC, JSDerouet commented on public/assets/css/contact.css
> +
ligne vide

2022-04-27 09:36 UTC, JSDerouet commented on public/assets/css/contact.css
> +
ligne vide

2022-04-27 09:44 UTC, JSDerouet commented on src/View/contact.html.twig
> +							</option>
retou à la ligne?

2022-04-27 09:52 UTC, Ysedda commented on public/assets/css/contact.css
> +
+ manque de saut de ligne après chaque sélecteur

2022-04-27 09:52 UTC, Ysedda commented on src/Controller/ContactController.php
> +
espace de trop

2022-04-27 09:52 UTC, Ysedda commented on src/Controller/ContactController.php
> +
espace de trop

2022-04-27 09:52 UTC, Ysedda commented on src/Controller/ContactController.php
> +    }
manque un espace

2022-04-27 09:52 UTC, Ysedda commented on src/Controller/ContactController.php
> +    private function validateFormat(array $contact): array
same

2022-04-27 09:52 UTC, Ysedda commented on src/Controller/ContactController.php
> +        $errorsTwo = null;
J'aurais plutôt appelé $errorsTwo -> $formatErrors histoire d'être cohérent avec les méthodes

2022-04-27 10:31 UTC, DESCARAVAGE commented
j'ai pas trop compris les espaces vides, j'ai comparé avec AdminClothController pour gérer les espaces.

2022-04-27 13:23 UTC, Chloebert requested changes

2022-04-27 13:23 UTC, Chloebert commented on src/View/Item/_form.html.twig
>  {# TODO : manage errors display #}
A supprimé et il faut enlever l'espace en dessous

2022-04-27 13:23 UTC, Chloebert commented on src/Controller/ContactController.php
> +    }
Toujours espace manquant

2022-04-27 13:23 UTC, Chloebert commented on src/View/contact.html.twig
> +	{# TODO : manage errors display #}
A supprimé

2022-04-27 14:39 UTC, JSDerouet approved these changes

2022-04-28 07:20 UTC, ThibaultFoure requested changes

2022-04-28 07:20 UTC, ThibaultFoure commented on src/View/contact.html.twig
> +				{% if errorsEmpty is not empty and errorsFormat is not empty %}
On regardera ta gestion des erreurs il faut simplifier cette partie

2022-04-28 07:20 UTC, ThibaultFoure commented on src/View/contact.html.twig
> +						<textarea name="message" id="message" rows="8" cols="936" placeholder="Votre message..."></textarea>
936 c'est peut-être léger tu devrais mettre au moins 8 000

2022-04-28 07:42 UTC, DESCARAVAGE commented on src/Controller/ContactController.php
> +            $errorsEmpty[] = "Le email est obligatoire";
c'est changé !

2022-04-28 07:43 UTC, DESCARAVAGE commented on src/Controller/ContactController.php
> +    public function index(): string
c'est changé !

2022-04-28 07:45 UTC, DESCARAVAGE commented on src/View/contact.html.twig
> +			<form>
c'est changé !

2022-04-28 08:09 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    padding-left: var(--spacing);
c'est fait bg !!

2022-04-28 08:12 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    margin-bottom:var(--spacing);
c'est fait aussi !

2022-04-28 08:18 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    margin-top: var(--spacing);
également fait !

2022-04-28 08:27 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    color: var(--bs-dark);
c'est géré !!

2022-04-28 08:51 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    border: none;
c'est fait !

2022-04-28 08:53 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    border: none;
okay !

2022-04-28 09:07 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    color:var(--bs-dark);
c'est fait !

2022-04-28 09:16 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    font-family: var(--text-font);
oui mais quand je mets dans les différentes classe de bootstrap ça ne fonctionne pas ... j'attends ta venue !

2022-04-28 09:19 UTC, DESCARAVAGE commented on src/View/contact.html.twig
> +						<textarea name="message" id="message" rows="8" cols="936" placeholder="Votre message..."></textarea>
c'est pour ca fasse la largueur de mon champ object...

2022-04-28 09:48 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    border-color: var(--bs-secondary);
okay !!

2022-04-28 09:48 UTC, DESCARAVAGE commented on public/assets/css/contact.css
> +    padding: 15px 25px;
okay !!

2022-04-28 09:58 UTC, DESCARAVAGE commented on src/View/contact.html.twig
> +				{% if errorsEmpty is not empty and errorsFormat is not empty %}
je n'ai pas trouvé avec l'aide de mes collègues j'attends ton expertise d'expert !!

2022-04-28 10:05 UTC, JSDerouet approved these changes

2022-04-28 14:33 UTC, baloolc requested changes

2022-04-28 14:33 UTC, baloolc commented on public/assets/css/contact.css
> +
ligne vide

2022-04-28 14:33 UTC, baloolc commented on src/View/contact.html.twig
> +
ligne vide

2022-04-28 14:33 UTC, baloolc commented on src/routes.php
> +
ligne vide

2022-04-28 15:00 UTC, baloolc submitted a review, later dismissed

2022-04-29 07:58 UTC, ThibaultFoure requested changes

2022-04-29 07:58 UTC, ThibaultFoure commented on src/routes.php
> +
effectivement, à suppr

2022-04-29 07:58 UTC, ThibaultFoure commented on public/assets/css/style.css
> +}
supprime cette partie, ça évitera un conflit ça a déjà été modifié

2022-04-29 08:34 UTC, ThibaultFoure approved these changes

2022-04-29 08:34 UTC, merged