S2 us 22 catégories machines
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #124
Opened 2022-04-27 14:29 UTC by JSDerouet

2022-04-27 15:15 UTC, Ysedda approved these changes

2022-04-28 08:16 UTC, ThibaultFoure approved these changes

2022-04-28 08:17 UTC, ThibaultFoure requested changes

2022-04-28 08:17 UTC, ThibaultFoure commented on src/Controller/AdminMachineController.php
> +    private function machineValidate(array $machine): array
petit changement ici

2022-04-28 08:42 UTC, Ysedda approved these changes

2022-04-28 08:55 UTC, ThibaultFoure approved these changes

2022-04-28 08:55 UTC, merged