finish view machineUser 1.0
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #245
Opened 2022-05-04 07:50 UTC by JSDerouet

2022-05-04 08:18 UTC, Chloebert submitted a review, later dismissed

2022-05-04 10:33 UTC, ThibaultFoure requested changes
attention au nommage des PR
nommage des fichiers également, pour la vue products, la vue générale est index, la vue d'un product précis est show

2022-05-04 10:33 UTC, ThibaultFoure commented on src/View/Products/machine.html.twig
> +			{% endif %}
à revoir comme on a dit

2022-05-04 10:33 UTC, ThibaultFoure commented on src/View/Products/machine.html.twig
> +					<a href='/tissus/categorie?id={{ clothCategory.id }}' class="btn btn-lg bg-primary w-100 m-1 categories">{{ clothCategory.name }}</a>
tu as fait comme Daniel, ce n'est pas pertinent d'avoir la même classe 'categories' sur une div qui contient plusieurs éléments et un lien/bouton, de plus vérfie que tu utilise cette classe, sinon supprime la

2022-05-04 10:33 UTC, ThibaultFoure commented on src/View/Products/machine.html.twig
> +					<a href='/machines' class="btn btn-lg w-100 bg-primary m-1 categories">{{ machineCategory.name }}</a>
ici aussi

2022-05-04 10:33 UTC, ThibaultFoure commented on src/View/Products/machine.html.twig
> +	<div class="container categories mt-3">
pas de container dans un container

2022-05-04 10:33 UTC, ThibaultFoure commented on src/View/Products/machine.html.twig
> +	<div class="container cards-products mt-3 mb-4">
container

2022-05-04 15:25 UTC, Chloebert requested changes

2022-05-05 09:08 UTC, Chloebert submitted a review, later dismissed

2022-05-05 10:21 UTC, ThibaultFoure submitted a review, later dismissed

2022-05-05 12:33 UTC, ThibaultFoure approved these changes

2022-05-05 12:33 UTC, merged