S3 us31 lexicon show
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #260
Opened 2022-05-04 13:27 UTC by JSDerouet

2022-05-04 13:34 UTC, baloolc approved these changes

2022-05-04 14:09 UTC, ThibaultFoure requested changes
C'est ok, mais ton fichier de vue doit s'appeler index et non show comme c'est la vue qui liste tous tes lexicons

2022-05-04 14:29 UTC, Ysedda submitted a review, later dismissed

2022-05-04 14:58 UTC, ThibaultFoure requested changes
j'arrive

2022-05-04 15:21 UTC, Chloebert approved these changes

2022-05-04 15:26 UTC, ThibaultFoure approved these changes

2022-05-05 08:45 UTC, ThibaultFoure approved these changes

2022-05-05 08:45 UTC, merged