S03 us38 admin add tutorial
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #298
Opened 2022-05-05 14:29 UTC by Ysedda

2022-05-05 16:25 UTC, Chloebert submitted a review, later dismissed

2022-05-06 08:10 UTC, ThibaultFoure requested changes

2022-05-06 08:10 UTC, ThibaultFoure commented on src/Controller/AdminTutorialController.php
> +            $tutorialErrors[] = 'Le nom ne doit pas dépasser les 100 caractères';
Réutilise ta constante dans ton affichage

2022-05-06 14:36 UTC, Chloebert approved these changes

2022-05-06 15:08 UTC, merged