Fix responsive de home page
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #346
Opened 2022-05-09 18:02 UTC by Chloebert

2022-05-09 18:20 UTC, JSDerouet submitted a review, later dismissed

2022-05-10 07:17 UTC, ThibaultFoure requested changes

2022-05-10 07:17 UTC, ThibaultFoure commented on public/assets/css/home.css
> +@media (max-width: 600px) {
C'est non

2022-05-10 07:57 UTC, JSDerouet approved these changes

2022-05-10 08:10 UTC, ThibaultFoure approved these changes

2022-05-10 08:10 UTC, merged