S1 us1 navbar
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #61
Opened 2022-04-20 14:59 UTC by baloolc

2022-04-21 08:25 UTC, DESCARAVAGE submitted a review, later dismissed

2022-04-21 08:40 UTC, JSDerouet approved these changes

2022-04-21 09:00 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +			<!-- JavaScript Bundle with Popper -->
code commenté

2022-04-21 09:01 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymou
même remarque que pour le css, le lien Bootstrap JS à mettre au dessus du block javascript

2022-04-21 09:04 UTC, ThibaultFoure requested changes
changements

2022-04-21 13:40 UTC, DESCARAVAGE submitted a review, later dismissed

2022-04-21 13:44 UTC, JSDerouet approved these changes

2022-04-21 13:52 UTC, ThibaultFoure commented on src/View/Component/_navbar.html.twig
> +						<a class="nav-link " aria-current="page" href="#">Accueil</a>
> espace vide

Toujours d'actualité

2022-04-21 16:36 UTC, baloolc commented on public/assets/css/style.css
> +    --bs-primary-rgb: 255, 244, 226;
ils y sont sur mes fichiers

2022-04-22 07:22 UTC, DESCARAVAGE submitted a review, later dismissed

2022-04-22 08:04 UTC, DESCARAVAGE approved these changes

2022-04-22 08:19 UTC, ThibaultFoure approved these changes

2022-04-22 08:19 UTC, merged