16 home
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #62
Opened 2022-04-21 09:03 UTC by Chloebert

2022-04-21 13:48 UTC, JSDerouet approved these changes

2022-04-21 13:53 UTC, baloolc requested changes

2022-04-21 13:53 UTC, baloolc commented on database.sql
> +(2, 'Doodads'),
Il faut pas que tu touche à la base de donné car il faut que l'on à tous la même 'thibault nous la dit'

2022-04-21 13:53 UTC, baloolc commented on src/View/Home/index.html.twig
> +					Lorem ipsum dolor sit amet consectetur adipisicing elit.
Il ne faut pas de lorem ipsum

2022-04-21 13:53 UTC, baloolc commented on src/View/layout.html.twig
>  				<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymo
Il ne faut pas mettre le block js dans les blocks

2022-04-21 13:53 UTC, baloolc commented on src/View/Home/index.html.twig
> +				<img src="https://picsum.photos/id/239/350/200" class="boutique-img m-2" alt="...">
il faut mettre un alt même si c'est pas très représentatif

2022-04-21 13:53 UTC, baloolc commented on public/assets/css/style.css
> +}
tu dois créer un fichier  .css et import sur le fichier style.css

2022-04-21 13:53 UTC, baloolc commented on public/assets/css/style.css
>      --spacing: 8px;
la variable spacing n'est pas nécessaire car gérer par bootstrap

2022-04-21 15:13 UTC, Chloebert commented on src/View/Home/index.html.twig
> +					Lorem ipsum dolor sit amet consectetur adipisicing elit.
Je me souviens plus, ça avait été dit en cours?

2022-04-21 15:16 UTC, Chloebert commented on public/assets/css/style.css
>      --spacing: 8px;
La variable spacing avait été approuvée lors du merge dans la dev, je n'y ai pas re-touché, mais je peux la supprimer éventuellement.

2022-04-21 15:19 UTC, Chloebert commented on public/assets/css/style.css
> +}
Tu veux dire créer un tout autre fichier avec ce que j'ai ajouté à part les variables..?

2022-04-22 08:02 UTC, DESCARAVAGE submitted a review, later dismissed

2022-04-22 08:18 UTC, ThibaultFoure requested changes
image trop grande, max 100 ko

2022-04-22 08:18 UTC, ThibaultFoure commented on public/assets/css/home.css
> +
display, align items, justify, text align, margin, padding, position, color, width à gérer en Bootstrap

2022-04-22 08:18 UTC, ThibaultFoure commented on src/Controller/HomeController.php
> +        return $this->twig->render('Home/index.html.twig', ['items' => $items]);
Pourquoi utiliser Item alors que c'est une table dont vous ne vous servez pas ?

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +			<br>
Aie aie aie les \<br\> en dehors des \<p\> sont illégaux

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +				<img src="https://picsum.photos/id/239/350/200" class="boutique-img m-2" alt="...">
le changement a été fait ? je vois toujours "..."

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +					Lorem ipsum dolor sit amet consectetur adipisicing elit.
Pareil ici, si le changement a été fait je ne le vois pas j'ai toujours du lorem

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +				{% for item in items %}
il faut utiliser les vraies données de votre bdd, la table items ne contient pas vos produits

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +		<link rel="stylesheet" href="/assets/css/home.css">
le style propre a ta page home est à inclure sur la page home et non dans le layout :wink:

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/layout.html.twig
> +			{% include '_slogan.html.twig'%}
Le slogan doit apparaitre sur toutes les pages ? Si oui il est à sa place sinon il faut le mettre uniquement là ou il doit apparaitre

2022-04-22 08:18 UTC, ThibaultFoure commented on src/View/layout.html.twig
>  				<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymo
le script js de bootstrap est à mettre au dessus du block javascript

2022-04-22 09:12 UTC, Chloebert commented on src/View/layout.html.twig
> +			{% include '_slogan.html.twig'%}
Il doit être sur toutes les pages, oui !

2022-04-22 14:01 UTC, DESCARAVAGE approved these changes

2022-04-25 14:34 UTC, ThibaultFoure requested changes

2022-04-25 14:34 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +			<h2 class="d-flex justify-content-center text-dark">Nos nouveautées
text-center fera la même chose que d-flex + justify-content-center

2022-04-25 14:34 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +							<img src="https://picsum.photos/200/200" class="card-img-top" alt="nouveautée tissus">
Peut-être rajouter le nom du tissu dans le alt ? Car tous les tissus auront le même alt sinon

2022-04-25 14:34 UTC, ThibaultFoure commented on src/View/Home/index.html.twig
> +								<p class="card-text text-dark mb-5">Voici notre nouveau produit.
mêmes remarques que la catégorie cloth

2022-04-25 14:34 UTC, ThibaultFoure commented on src/View/_slogan.html.twig
> +<div class="container d-flex justify-content-center mt-2 mb-2">
le fichier serait à placer dans votre dossier Component plutot

2022-04-25 14:37 UTC, Chloebert commented on public/assets/css/style.css
> +    line-height: 1.5;
On doit plutôt le mettre dans body?

2022-04-25 14:50 UTC, Chloebert commented on src/View/Home/index.html.twig
> +								<p class="card-text text-dark mb-4">Voici notre nouveau produit.
Dans l'idée on va rajouter une entrée dans la BDD. Est-ce qu'il faudrait mieux le faire maintenant avant de push ou est-ce que je peux modifier ça plus tard?

2022-04-26 11:54 UTC, Ysedda approved these changes

2022-04-26 13:46 UTC, ThibaultFoure approved these changes

2022-04-26 13:47 UTC, merged