S01 us18 cloth admin
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #64
Opened 2022-04-21 15:12 UTC by Ysedda

2022-04-21 18:06 UTC, baloolc submitted a review, later dismissed

2022-04-22 07:37 UTC, Chloebert approved these changes

2022-04-22 07:56 UTC, ThibaultFoure requested changes

2022-04-22 07:56 UTC, ThibaultFoure commented on public/assets/css/adminstyle.css
> +    text-align:center;
margin et text-align possibles en bootstrap

2022-04-22 07:56 UTC, ThibaultFoure commented on src/View/Admin/Cloth/_form.html.twig
> +<h2 class="addclothtitle col-8 col-md-6 mx-auto">Ajouter un tissu</h2>
camelCase

2022-04-22 07:56 UTC, ThibaultFoure commented on src/View/adminLayout.html.twig
> +<!doctype html>
beaucoup de code en commun, il serait judicieux de faire un extend du layout.html.twig et faire les modifs nécessaires ensuite

2022-04-22 08:18 UTC, DESCARAVAGE approved these changes

2022-04-22 08:23 UTC, ThibaultFoure approved these changes

2022-04-22 08:23 UTC, merged