Us15 7 produits categories
WildCodeSchool/2022-03-php-orleans-project-tissusjaures pull request #65
Opened 2022-04-21 15:12 UTC by Chloebert

2022-04-21 16:49 UTC, Ysedda approved these changes

2022-04-22 08:12 UTC, DESCARAVAGE approved these changes

2022-04-22 14:00 UTC, DESCARAVAGE approved these changes

2022-04-26 14:32 UTC, baloolc submitted a review, later dismissed

2022-04-26 15:17 UTC, Ysedda approved these changes

2022-04-26 15:27 UTC, ThibaultFoure requested changes

2022-04-26 15:27 UTC, ThibaultFoure commented on src/View/Products/index.html.twig
> +	<link rel="stylesheet" href="/assets/css/home.css">
C'est le soucis dont on a parlé avec Sylvain tout à l'heure, tu n'es pas censée avoir besoin de home.css et de products.css ici, si tu as du style commun a ces deux fichiers il devrait être dans style.css, et le style spécifique à cette page Products/index doit être dans products.css, pareil pour home.css c'est le style spécifique à la page home

2022-04-26 18:02 UTC, Ysedda approved these changes

2022-04-26 18:07 UTC, merged